version: '3.8'
services:
  bot:
    build: .
    container_name: nexzy-clear-bot
    restart: always
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./data:/app/data
      - ./secret.key:/app/secret.key