version: '3.8'
services:
  bot:
    build: .
    container_name: nexzy-clear-bot-v4
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    volumes:
      - ./data:/app/data
