version: '3.8'
services:
  bot:
    build: .
    container_name: bot-limpar-dm-bot
    restart: always
    # network_mode: "host"   # REMOVIDO para permitir DNS personalizado
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - data:/app

volumes:
  data: